# Spell Checker



Una de las primeras aplicaciones de los modelos de IA en problemas de lenguaje (además de los clasificadores de spam) los modelos fueron los correctores ortotipográficos. Existen diferentes formas de atacar ese problema (IA tradicional, Machine Learning, Deep Learning...).

Desde la perspectiva del Machine learning supervisado necesitaríamos un dataset (o corpus) de palabras con errores y su correspondiente palabra correcta como target. Por ejemplo, podríamos generar el siguiente corpus de palabras a partir de 100 años de soledad

## Dataset

In [1]:
import re
import requests


url = "https://gist.githubusercontent.com/ismaproco/6781d297ee65c6a707cd3c901e87ec56/raw/20d3520cd7c53d99215845375b1dca16ac827bd7/gabriel_garcia_marquez_cien_annos_soledad.txt"
text = requests.get(url).text.lower()  # Convertimos a minúsculas

# Tokenizamos palabras (solo a-z)
words = re.findall(r'\b[a-záéíóúñü]+\b', text)

# Quitamos duplicados para tener vocabulario
vocab = list(set(words))
print("Número de palabras únicas en el vocabulario:", len(vocab))
print(words[0:30])

Número de palabras únicas en el vocabulario: 15692
['gabriel', 'garcía', 'márquez', 'cien', 'años', 'de', 'soledad', 'editado', 'por', 'ediciones', 'la', 'cueva', 'para', 'j', 'omi', 'garcía', 'ascot', 'y', 'maría', 'luisa', 'elio', 'cien', 'años', 'de', 'soledad', 'gabriel', 'garcía', 'márquez', 'muchos', 'años']

## Canal de ruido

A partir del lenguaje natural podemos obtener palabras, pero cuesta mucho buscar/generar errores manualmente. Para este problema en el NLP se usaba una técnica que se denomina "canal de ruido" Que permite generar un dataset artificial a partir de una función que genera errores

In [ ]:
import numpy as np

# Mapa simple QWERTY (fila, columna)
keyboard = {
    'q': (0,0), 'w': (0,1), 'e': (0,2), 'r': (0,3), 't': (0,4), 'y': (0,5), 'u': (0,6), 'i': (0,7), 'o': (0,8), 'p': (0,9),
    'a': (1,0), 's': (1,1), 'd': (1,2), 'f': (1,3), 'g': (1,4), 'h': (1,5), 'j': (1,6), 'k': (1,7), 'l': (1,8), 'ñ': (1,9),  "'" : (1,10),
    'z': (2,0), 'x': (2,1), 'c': (2,2), 'v': (2,3), 'b': (2,4), 'n': (2,5), 'm': (2,6)
}

> **NOTA**: Usamos esta forma de "vectorizar" los caracteres (sin tokenizar y vectorizar como hemos visto antes) porque es conveniente para representar las letras en un teclado. Desde una perspectiva mecánica, las "features" de una letra en el teclado es su posición en términos de fila y columna

In [ ]:
import random

def generate_typo(word, error_prob=0.1):

    # Elegimos aleatoriamente la posición del error
    pos = random.randint(0, len(word)-1)

    # obtener posición
    x, y = keyboard[word[pos]]

    # letras cercanas
    neighbors = [c for c in keyboard if (keyboard[c][0] in [x-1,x+1]) and (keyboard[c][1] in [y-1,y+1])]

    # Elegir una letra
    wrong_character = random.choice(neighbors)

    # Reemplazamos el caracter en la posición elegida
    word = word[:pos] + wrong_character + word[pos+1:]

    return word

In [ ]:
generate_typo('hola')

'hopa'

El objetivo de este ejercicio es usar la función generate_typo para hacer un modelo de aprendizaje supervisado que aprenda a corregir errores

<br>

---

### Preprocesado de texto

Para poder corregir errores de tilde, representamos la tilde como un caracter separado a la vocal

In [ ]:
import unicodedata

def preprocess_text(text):
    """
    Convierte caracteres acentuados en letra base + apóstrofe.
    Ejemplo: 'í' -> "i'"
    """

    text = text.lower()
    text= text.replace("ñ","___")

    # Normalizamos el string a NFD (decomposición)
    text = unicodedata.normalize('NFD', text)

    # Reemplazamos cualquier diacrítico (acento) por apostrofe
    text = ''.join("'" if unicodedata.combining(c) else c for c in text)

    text = text.replace("___","ñ")
    return text

# Ejemplos de uso
print(preprocess_text("buendía"))
print(preprocess_text("hola"))
print(preprocess_text("años"))

buendi'a
hola
años

In [ ]:
words = [preprocess_text(word) for word in words]

<br>

### Generación de errores

La tarea de nuestro modelo es "corregir palabras mal escritas" por tanto necesitamos que aprenda, a partir de una palabra mal escrita cual ese la palabra correcta (target)

In [ ]:
import pandas as pd

corpus = pd.DataFrame(
    {
        "typo": [generate_typo(word) for word in words],
        "word": words,
    }
)
corpus

            typo      word
0        gabdiel   gabriel
1        gwrci'a   garci'a
2       mw'rquez  ma'rquez
3           clen      cien
4           añoq      años
...          ...       ...
139129       xvj       xvi
139130      xvji      xvii
139131     xvlii     xviii
139132       xjx       xix
139133        xd        xx

[139134 rows x 2 columns]

<br>

## Limpieza de datos

Eliminamos los errores que dan lugar a una palabra que esté bien escrita. Además también tenemos en cuenta solo palabras de más de 1 caracter

In [ ]:
corpus = corpus[
    corpus.apply(lambda row: row.typo not in vocab, axis=1)
][
    corpus.word.str.len() > 1 # Cogemos palabras de más de una letra
][
    corpus.word.str.len() < 15 # No cogemos palabras de más de 15 letras
].reset_index(drop=True)

corpus

/tmp/ipython-input-774576386.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data = data[
/tmp/ipython-input-774576386.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  data = data[

            typo      word
0        gabdiel   gabriel
1        gwrci'a   garci'a
2       mw'rquez  ma'rquez
3           clen      cien
4           añoq      años
...          ...       ...
125717       xvj       xvi
125718      xvji      xvii
125719     xvlii     xviii
125720       xjx       xix
125721        xd        xx

[125722 rows x 2 columns]

### Vectorización

Añadimos el token de "fin de palabra" al keyboard. Esto es algo relativo al modelo de machine learning. Le damos un valor muy distinto al resto de letras para diferenciarlo

In [ ]:
keyboard["</s>"] = (99,99)

Vectorizar consiste en atribuir features numéricas a un texto. En este caso la vectorización la hacemos a partir de la posición de las letras en vez de seguir un acercamiento más probabilístico como n-gramas y count vectorizer

In [ ]:
MAX_LEN = 15  # el número de features tiene que ser fijo así que definimos como "15" el número máximo de letras que puede tener una palabra

def word_to_vector(word):
    vec = []

    for i in range(MAX_LEN):
        if len(word) > i:
            vec = vec + list(keyboard[word.lower()[i]])
        else:
            vec = vec + list(keyboard["</s>"])

    # truncar si es más largo
    return np.array(vec[:MAX_LEN*2])

word_to_vector("hola")

array([ 1,  5,  0,  8,  1,  8,  1,  0, 99, 99, 99, 99, 99, 99, 99, 99, 99,
       99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

### Dataset

Para que el corpus de palabras nos sirva como dataset de entrenamiento guardamos las features en un dataframe

In [ ]:
dataset = pd.DataFrame(
    [word_to_vector(word) for word in corpus.typo]
).assign(word=corpus.word
).assign(typo=corpus.typo
).set_index('typo')

dataset

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,word
typo,,,,,,,,,,,,,,,,,,,,,
gabdiel,1,4,1,0,2,4,1,2,0,7,...,99,99,99,99,99,99,99,99,99,gabriel
gwrci'a,1,4,0,1,0,3,2,2,0,7,...,99,99,99,99,99,99,99,99,99,garci'a
mw'rquez,2,6,0,1,1,10,0,3,0,0,...,99,99,99,99,99,99,99,99,99,ma'rquez
clen,2,2,1,8,0,2,2,5,99,99,...,99,99,99,99,99,99,99,99,99,cien
añoq,1,0,1,9,0,8,0,0,99,99,...,99,99,99,99,99,99,99,99,99,años
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xvj,2,1,2,3,1,6,99,99,99,99,...,99,99,99,99,99,99,99,99,99,xvi
xvji,2,1,2,3,1,6,0,7,99,99,...,99,99,99,99,99,99,99,99,99,xvii
xvlii,2,1,2,3,1,8,0,7,0,7,...,99,99,99,99,99,99,99,99,99,xviii
xjx,2,1,1,6,2,1,99,99,99,99,...,99,99,99,99,99,99,99,99,99,xix
xd,2,1,1,2,99,99,99,99,99,99,...,99,99,99,99,99,99,99,99,99,xx

<br>

## Model

### train test split

In [ ]:
from sklearn.model_selection import train_test_split

X = dataset.drop(columns="word")
y = dataset.word

X_train, X_test, y_train, y_test = train_test_split(X,y)

### Train

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(
    n_neighbors=10,
    weights='distance',
    p=1
)

model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=10, p=1, weights='distance')

In [ ]:
# Ver qué vecinos usa el modelo para la predicción
vec_buenria = word_to_vector(preprocess_text("buenría"))
distances, indices = model.kneighbors([vec_buenria])

for i, (dist, idx) in enumerate(zip(distances[0], indices[0])):
    print(f"{i+1}. Distancia: {dist:.2f}, Palabra: {repr(y_train.iloc[idx])}")

1. Distancia: 0.00, Palabra: buendi'a
2. Distancia: 0.00, Palabra: buendi'a
3. Distancia: 0.00, Palabra: buendi'a
4. Distancia: 0.00, Palabra: buendi'a
5. Distancia: 0.00, Palabra: buendi'a
6. Distancia: 0.00, Palabra: buendi'a
7. Distancia: 0.00, Palabra: buendi'a
8. Distancia: 2.00, Palabra: buendi'a
9. Distancia: 2.00, Palabra: buendi'a
10. Distancia: 2.00, Palabra: buendi'a

### Evaluation

In [ ]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import classification_report

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.8696827972383953

In [ ]:
print(classification_report(y_test, y_pred))

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

                precision    recall  f1-score   support

         a'gil       0.00      0.00      0.00         1
       a'mbito       0.80      1.00      0.89         4
        a'nimo       1.00      0.33      0.50         3
       a'nimos       1.00      1.00      1.00         1
       a'rabes       1.00      1.00      1.00         6
        a'rbol       1.00      1.00      1.00         1
       a'ridas       0.00      0.00      0.00         1
        a'rido       1.00      1.00      1.00         1
       a'rmate       0.00      0.00      0.00         1
       a'spera       0.00      0.00      0.00         1
       a'spero       0.50      1.00      0.67         1
      a'speros       0.00      0.00      0.00         1
         aaaay       0.00      0.00      0.00         1
    abandonaba       0.17      1.00      0.29         1
   abandonaban       0.40      1.00      0.57         2
    abandonada       0.00      0.00      0.00         3
   abandonadas       0.00      0.00      0.00         1
    abandonado       1.00      1.00      1.00         2
   abandonados       0.00      0.00      0.00         0
   abandonando       0.00      0.00      0.00         1
     abandonar       1.00      1.00      1.00         4
    abandonara       0.00      0.00      0.00         2
   abandonarla       0.00      0.00      0.00         1
   abandonaron       0.25      1.00      0.40         1
     abandone'       0.00      0.00      0.00         1
     abandono'       0.80      1.00      0.89         4
 abanica'ndose       0.00      0.00      0.00         0
        abasto       0.00      0.00      0.00         1
      abatidos       0.00      0.00      0.00         1
         abeja       0.00      0.00      0.00         2
       abierta       0.40      1.00      0.57         2
      abiertas       1.00      1.00      1.00         1
       abierto       1.00      1.00      1.00         2
      abiertos       0.50      1.00      0.67         2
   abigarradas       1.00      1.00      1.00         1
    abigarrado       1.00      1.00      1.00         1
     ablandara       0.00      0.00      0.00         1
    ablandarle       0.00      0.00      0.00         1
    abochornar       0.00      0.00      0.00         1
      abogados       0.33      1.00      0.50         2
      aborigen       0.00      0.00      0.00         1
         abran       0.00      0.00      0.00         1
     abrasante       1.00      1.00      1.00         1
     abrazados       0.00      0.00      0.00         1
        abrazo       1.00      0.50      0.67         2
        abri'a       0.00      0.00      0.00         3
      abriendo       0.00      0.00      0.00         2
      abrieran       0.00      0.00      0.00         1
         abril       1.00      0.33      0.50         3
        abrio'       0.89      1.00      0.94         8
         abrir       0.67      1.00      0.80         4
      abriri'a       0.00      0.00      0.00         1
       abrirle       1.00      1.00      1.00         1
       abrirlo       0.00      0.00      0.00         1
       abrirse       1.00      1.00      1.00         1
     abrumador       0.00      0.00      0.00         1
     abrumados       0.00      0.00      0.00         0
       abrupta       0.00      0.00      0.00         1
      absoluta       1.00      1.00      1.00         1
       absorta       0.00      0.00      0.00         2
       absorto       0.67      1.00      0.80         4
       absurda       1.00      1.00      1.00         1
       absurdo       0.00      0.00      0.00         1
        abuela       1.00      1.00      1.00         1
      abuelito       0.00      0.00      0.00         1
        abuelo       0.78      1.00      0.88         7
  aburrimiento       0.00      0.00      0.00         1
    abyeccio'n       0.00      0.00      0.00         1
       acababa       1.00      1.00      1.00         3
      acababan       0.00      0.00      0.00         0
       acabado       0.50      1.00      0.67         1
        acaban       0.00      0.00      0.00         1
      acabando       0.00      0.00      0.00         2
        acabar       0.50      1.00      0.67         1
       acabara       1.00      1.00      1.00         1
      acabaran       0.00      0.00      0.00         1
      acabaron       0.50      1.00      0.67         1
        acabe'       0.00      0.00      0.00         1
        acaben       1.00      1.00      1.00         1
        acabo'       0.83      1.00      0.91         5
    acade'mica       0.00      0.00      0.00         1
      academia       0.00      0.00      0.00         1
     acallados       0.00      0.00      0.00         1
     acamparon       1.00      1.00      1.00         1
    acariciaba       0.00      0.00      0.00         0
    acartonada       0.33      1.00      0.50         1
         acaso       0.00      0.00      0.00         1
     accidente       0.00      0.00      0.00         0
      aceitaba       0.00      0.00      0.00         1
      aceitada       0.00      0.00      0.00         0
       aceite'       0.00      0.00      0.00         1
      aceptado       1.00      1.00      1.00         1
       aceptar       0.33      1.00      0.50         1
    aceptarlas       0.00      0.00      0.00         1
     aceptaron       1.00      1.00      1.00         1
        acepto       0.00      0.00      0.00         1
       acepto'       1.00      1.00      1.00         1
     acercaban       0.00      0.00      0.00         1
  acercamiento       0.00      0.00      0.00         1
     acercaron       0.00      0.00      0.00         0
     acercarse       0.00      0.00      0.00         0
         acere       0.00      0.00      0.00         1
         acero       0.00      0.00      0.00         0
      acezante       0.00      0.00      0.00         1
  achicharrado       1.00      1.00      1.00         1
       achiote       0.00      0.00      0.00         1
       aclarar       0.00      0.00      0.00         0
       aclaro'       0.00      0.00      0.00         2
      aco'nito       0.00      0.00      0.00         0
      acomode'       0.00      0.00      0.00         1
      acomodo'       0.00      0.00      0.00         1
acompaña'ndola       1.00      1.00      1.00         1
    acompañaba       1.00      1.00      1.00         1
     acompaño'       1.00      1.00      1.00         1
acontecimiento       1.00      1.00      1.00         1
      acordaba       0.00      0.00      0.00         0
      acordara       0.00      0.00      0.00         1
     acordarse       0.75      1.00      0.86         3
     acordeo'n       1.00      1.00      1.00         6
       acordo'       0.00      0.00      0.00         1
          acos       0.00      0.00      0.00         1
       acosada       0.00      0.00      0.00         1
  acosta'ndola       0.00      0.00      0.00         1
  acosta'ndose       0.00      0.00      0.00         1
     acostaban       0.50      1.00      0.67         1
     acostando       0.00      0.00      0.00         1
     acostarse       1.00      1.00      1.00         3
       acosto'       0.20      1.00      0.33         1
  acostumbraba       0.00      0.00      0.00         1
  acostumbrada       0.00      0.00      0.00         2
 acostumbradas       0.00      0.00      0.00         0
  acostumbrado       0.20      1.00      0.33         1
 acostumbrados       0.00      0.00      0.00         1
 acostumbraron       0.00      0.00      0.00         2
 acostumbrarse       0.00      0.00      0.00         0
    acreditaba       1.00      1.00      1.00         1
       actitud       0.75      1.00      0.86         3
     actividad       1.00      1.00      1.00         2
        activo       0.00      0.00      0.00         1
          acto       0.67      1.00      0.80         4
         actos       0.00      0.00      0.00         2
        actual       1.00      1.00      1.00         1
     acua'tica       0.00      0.00      0.00         1
     acuarelas       0.00      0.00      0.00         1
   acuartelada       0.00      0.00      0.00         1
       acudio'       1.00      1.00      1.00         2
       acuerda       0.00      0.00      0.00         2
       acuerdo       0.82      1.00      0.90         9
     acumulado       1.00      1.00      1.00         1
      acumular       0.00      0.00      0.00         1
    acusacio'n       0.00      0.00      0.00         1
       acusado       0.00      0.00      0.00         2
            ad       0.00      0.00      0.00         1
      adecuada       1.00      1.00      1.00         1
      adecuado       0.00      0.00      0.00         0
       adema's       1.00      1.00      1.00         4
      ademanes       0.33      1.00      0.50         1
     adheridos       0.00      0.00      0.00         1
  adiestrari'a       0.00      0.00      0.00         1
  adiestrarlos       0.00      0.00      0.00         0
        adio's       1.00      1.00      1.00         2
       adioses       0.00      0.00      0.00         1
     adivinaba       0.25      1.00      0.40         1
   adivinanzas       1.00      1.00      1.00         1
       adivino       0.00      0.00      0.00         1
      admiraba       0.00      0.00      0.00         1
   admiracio'n       0.00      0.00      0.00         0
       admirar       0.00      0.00      0.00         1
      admiti'a       1.00      1.00      1.00         1
     admiti'an       0.00      0.00      0.00         1
      admitio'       0.50      1.00      0.67         1
  adolescencia       0.56      1.00      0.71         5
   adolescente       1.00      1.00      1.00         1
  adolescentes       0.00      0.00      0.00         3
    adoquinada       0.00      0.00      0.00         1
   adora'ndose       0.00      0.00      0.00         1
   adormecidos       0.00      0.00      0.00         1
     adquirido       1.00      1.00      1.00         2
     adquirio'       0.50      1.00      0.67         1
       adultos       1.00      0.50      0.67         2
    aduraznado       0.00      0.00      0.00         1
    advenedizo       0.00      0.00      0.00         1
   advenedizos       0.00      0.00      0.00         0
    adversario       1.00      1.00      1.00         1
   adversarios       0.00      0.00      0.00         0
      adversas       0.00      0.00      0.00         1
    adversidad       0.00      0.00      0.00         1
   advirtieran       0.00      0.00      0.00         1
     advirtio'       0.88      1.00      0.93         7
     adyacente       1.00      1.00      1.00         1
        ae'rea       0.00      0.00      0.00         1
     aeroplano       1.00      1.00      1.00         3
     afectaron       0.00      0.00      0.00         1
        afecto       0.33      0.33      0.33         3
       afectos       1.00      1.00      1.00         3
       afeitar       0.00      0.00      0.00         2
     afeitarle       0.00      0.00      0.00         1
     afeitarse       0.50      1.00      0.67         1
  aferra'ndose       0.00      0.00      0.00         0
      aficio'n       0.00      0.00      0.00         0
      afiladas       0.00      0.00      0.00         1
       afirmo'       0.00      0.00      0.00         0
    afliccio'n       0.50      1.00      0.67         2
     afligidas       0.00      0.00      0.00         0
     afligidos       0.00      0.00      0.00         1
      aflojaba       0.00      0.00      0.00         1
     agarrando       0.00      0.00      0.00         0
     agarrarse       0.00      0.00      0.00         1
       agarro'       0.50      1.00      0.67         1
    agitacio'n       0.00      0.00      0.00         2
      agitador       0.00      0.00      0.00         1
      agobiada       1.00      1.00      1.00         2
      agobiado       0.00      0.00      0.00         0
       agoni'a       1.00      1.00      1.00         1
    agonizando       1.00      1.00      1.00         1
        agosto       0.75      1.00      0.86         3
      agotador       0.00      0.00      0.00         2
   agotamiento       0.00      0.00      0.00         2
      agotando       0.00      0.00      0.00         1
        agoto'       0.00      0.00      0.00         1
       agradar       0.00      0.00      0.00         1
    agradecido       0.00      0.00      0.00         1
       agravo'       1.00      1.00      1.00         1
       agrego'       1.00      1.00      1.00         2
   agresividad       1.00      1.00      1.00         2
       agresor       0.00      0.00      0.00         1
     agrietado       0.00      0.00      0.00         0
    agrietados       0.00      0.00      0.00         1
  agrimensores       0.00      0.00      0.00         0
    agro'nomos       1.00      1.00      1.00         1
          agua       1.00      1.00      1.00         9
      aguacero       1.00      1.00      1.00         1
         aguas       1.00      0.67      0.80         3
       aguilar       0.80      1.00      0.89         8
        agujas       1.00      1.00      1.00         1
          ahi'       0.83      1.00      0.91         5
       ahi'nco       1.00      1.00      1.00         1
   ahoga'ndose       0.33      1.00      0.50         1
       ahogaba       0.00      0.00      0.00         1
       ahogado       0.00      0.00      0.00         0
         ahora       1.00      1.00      1.00        10
       ahorros       0.00      0.00      0.00         0
    ahuyentaba       0.00      0.00      0.00         1
          aire       0.88      1.00      0.94        15
         aires       0.00      0.00      0.00         1
         ajena       0.50      0.50      0.50         2
        ajenas       0.00      0.00      0.00         1
         ajeno       1.00      1.00      1.00         1
          ajos       1.00      0.33      0.50         3
         ajuar       0.00      0.00      0.00         1
      ajustado       0.00      0.00      0.00         1
     ajustados       0.00      0.00      0.00         0
        ajuste       0.00      0.00      0.00         1
            al       1.00      1.00      1.00       231
       alabama       0.00      0.00      0.00         1
  alabastrados       0.00      0.00      0.00         1
      alacra'n       1.00      1.00      1.00         1
        alados       0.00      0.00      0.00         1
     alambrada       1.00      1.00      1.00         2
     alambrado       1.00      1.00      1.00         2
       alambre       1.00      1.00      1.00         3
      alambres       0.00      0.00      0.00         1
          alar       0.00      0.00      0.00         1
        alarma       0.33      1.00      0.50         1
      alarmada       0.50      1.00      0.67         1
     alarmados       0.00      0.00      0.00         0
     alarmaron       0.00      0.00      0.00         1
       alarmo'       0.00      0.00      0.00         0
          alas       0.00      0.00      0.00         0
          alba       1.00      0.67      0.80         3
     albañiles       0.67      1.00      0.80         2
       alberca       1.00      1.00      1.00         2
    alborotada       0.00      0.00      0.00         1
   alborotados       0.00      0.00      0.00         2
   alborotaron       0.00      0.00      0.00         1
      alboroto       1.00      1.00      1.00         1
      alborozo       0.67      1.00      0.80         2
       alcalde       0.00      0.00      0.00         0
       alcance       0.33      1.00      0.50         1
    alcanzaban       1.00      1.00      1.00         1
     alcanzado       1.00      1.00      1.00         1
      alcanzar       1.00      1.00      1.00         1
   alcanzarlos       0.00      0.00      0.00         1
      alcanzo'       0.80      1.00      0.89         4
   alcaravanes       1.00      1.00      1.00         1
        alcoba       1.00      1.00      1.00         1
        aldaba       0.00      0.00      0.00         1
       aldabas       0.00      0.00      0.00         0
         aldea       0.92      1.00      0.96        12
       alegrar       0.00      0.00      0.00         1
        alegre       1.00      1.00      1.00         2
       alegres       0.50      0.50      0.50         2
      alegri'a       0.80      1.00      0.89         4
       alegro'       0.00      0.00      0.00         1
       alejaba       0.00      0.00      0.00         0
   alejandri'a       0.00      0.00      0.00         1
      alemanes       0.00      0.00      0.00         2
       alertas       0.00      0.00      0.00         0
     alexander       0.00      0.00      0.00         1
      alfabeto       0.00      0.00      0.00         1
     alfileres       1.00      1.00      1.00         1
      alforzas       0.00      0.00      0.00         1
          alga       1.00      1.00      1.00         1
         algas       0.00      0.00      0.00         1
          algo       0.84      1.00      0.91        16
      algodo'n       1.00      1.00      1.00         1
   algodonales       0.00      0.00      0.00         1
        algu'n       1.00      1.00      1.00         5
       alguien       1.00      1.00      1.00        13
        alguna       0.71      1.00      0.83         5
       algunas       0.33      1.00      0.50         1
        alguno       0.57      1.00      0.73         4
       algunos       0.57      1.00      0.73         4
       aliento       1.00      1.00      1.00         4
    alimentaba       0.50      1.00      0.67         1
   alimentando       0.50      1.00      0.67         1
   alimentaran       0.00      0.00      0.00         1
      alimento       0.00      0.00      0.00         1
     alimentos       0.00      0.00      0.00         3
     alistaban       0.00      0.00      0.00         1
      aliviaba       0.00      0.00      0.00         1
      aliviara       0.00      0.00      0.00         0
        alivio       1.00      1.00      1.00         1
       alivio'       0.00      0.00      0.00         1
         alla'       1.00      1.00      1.00         3
         alli'       0.91      1.00      0.95        10
          alma       0.50      1.00      0.67         2
     almendros       1.00      1.00      1.00         1
      almi'bar       0.00      0.00      0.00         0
    almidonado       1.00      1.00      1.00         1
      almizcle       0.00      0.00      0.00         1
      almo'far       0.00      0.00      0.00         1
     almohadas       0.00      0.00      0.00         1
   almohadilla       1.00      1.00      1.00         1
  almohadillas       0.00      0.00      0.00         0
      almorzar       0.75      1.00      0.86         3
      almorzo'       1.00      1.00      1.00         1
      almuerzo       1.00      1.00      1.00         3
      alquilar       0.00      0.00      0.00         1
    alquilaron       0.00      0.00      0.00         1
      alquilo'       0.00      0.00      0.00         1
      alquimia       1.00      1.00      1.00         3
    alquimista       0.00      0.00      0.00         1
    alquitra'n       0.00      0.00      0.00         0
     alrededor       1.00      1.00      1.00         2
          alta       0.75      1.00      0.86         3
       altamar       0.00      0.00      0.00         1
         altar       0.80      1.00      0.89         4
         altas       0.00      0.00      0.00         0
     alternaba       1.00      1.00      1.00         1
       altero'       0.50      1.00      0.67         1
   altisonante       0.00      0.00      0.00         0
  altisonantes       0.00      0.00      0.00         1
        altiva       0.00      0.00      0.00         1
          alto       1.00      0.40      0.57         5
        altura       0.00      0.00      0.00         2

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

<br>

## Código de Spell Checker

Como hemos dicho alguna vez, la IA no solo es el modelo y los datos, también es el código que lo usa. Aquí podemos ver cómo sería un código funcional que realmente corrigiese la palabra más allá de simplemente predecir

In [ ]:
def spell_checker(word):

    if word in vocab: # Si la palabra existe en el vocabulario no se corrige
        return word

     # Preprocesamos el texto
    processed_word = preprocess_text(word)

    # Lo convertimos a vector
    vec = word_to_vector(processed_word)

    # Predecimos la palabra
    new_word = model.predict([vec])[0]

    # Calculamos la probabilidad de la predicción
    proba =  model.predict_proba([vec]).max()

    # Si el modelo no da una probabilidad suficientemente alta no corregimos la palabra
    if proba <0.5:
        return word


    # Deshacemos el preprocesamiento
    replacements = {
        "a'": "á",
        "e'": "é",
        "i'": "í",
        "o'": "ó",
        "u'": "ú",
        "n'": "ñ",
    }

    for k, v in replacements.items():
        new_word = new_word.replace(k, v)

    # Copiamos capitalización
    new_word = list(new_word)
    for char in word:
        if char.isupper():
            new_word[0] = new_word[0].upper()

    return "".join(new_word)

In [ ]:
spell_checker("Buenría")

'Buendía'